### ISSUE TITLE
Continue Inclusion of Indexing Scanned CVIs in Scope?

### ISSUE THREAD

**Issue by AAVLD-USAHA-ITStandards** [AAVLD-USAHA-ITStandards/eCVI#1]
I feel like introducing embedded images/documents also introduces many other potential issues such as extremely large XML files, security concerns about embedded documents (e.g. virus scanning), data quality issues (e.g. DPI too low) and so on.  (Nate Plumm)

I’m torn here but probably feel this is not appropriate. To me the more Band-Aids we provide the longer it takes to move to a complete electronic process. Providing a means to support paper forms only delays States from enforcing electronic only ICVIs. It seems that many individuals believe once they are uploaded into a system the they are “electronic” and this is a false impression that gets promoted too often.  (Randy Munger)

**Comment by mkm1879** [comment]
I believe a number of implementations, even ones with full eCVIs, use the binary attachment feature.  This can carry the digitally signed document (digital signature being out of scope), printable images/pdfs, etc.  Has size been a significant problem for implementers?  

Image quality is an issue that could certainly be addressed, but probably in a separate effort.

**Comment by mmcgrath** [comment]
I think allowing for embedding the original image is worth it for one specific use case: we have a situation where customers will be encoding the information off a paper CVI into one of our products. They will want this information sent to the destination state electronically and we'll want to include the original source paper CVI as part of the message. This is for a multitude of reasons such as:

  * our users may have linked the record to a premises in their database that is slightly different to the information written on the form - we would not want to lose the originally hand-written information that was on the original paper form when sending the data to the receiving state
  * in many cases, the animal IDs are written in some type of abbreviated form on the paper document but this is "expanded" by the data input person during data entry into complete and valid animal IDs. Again, we wouldn't want to lose the original information written on the paper form by the veterinarian in the field.

I recommend retaining the `eCVI/Attachment` element as-is structurally; however, to pick up on Randy's concerns - maybe an annotation should be added to the Payload letting schema users know that attached files may be ignored unless that meet certain size parameters? For example, "PDF and image files at a maximum resolution of 300dpi; images must be in a compressed format such as PNG, GIF or JPG" If there is agreement on this annotation, let me know and I'll prepare a pull request.

**Comment by mkm1879** [comment]
I will close this issue.  We will add appropriate annotation to the schema and to accompanying documentation.
