### ISSUE TITLE
Breed

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#11]
With all the work on species, we've ignored breed.  It is currently a two or three character breed code with no enumeration.  It also lacks a free-text element.  Is this a concern for any of the implementations?

**Comment by sarahlcaffey** [comment]
In mCVI, we would like to allow for a "Breed Other" free-text element if possible.

**Comment by mkm1879** [comment]
Length restriction removed from Breed string field.  Documentation recommends standard codes when applicable.  Will close soon without objection.

**Comment by mkm1879** [comment]
Closing pending full committee vote.
