### ISSUE TITLE
Carrier Information

### ISSUE THREAD

**Issue by sarahlcaffey** [AAVLD-USAHA-ITStandards/eCVI#12]
Should we have a separate location for "Carrier" information if carrier is different than Consignor? In the current version of mCVI, we have a separate carrier section where users can enter name, phone, email, etc. for the carrier (all not required fields). As we work on the new version of mCVI, we are just wanting to determine the best place within the schema to map that info.

**Comment by mkm1879** [comment]
Closing pending full committee vote.
