### ISSUE TITLE
Transportation Information

### ISSUE THREAD

**Issue by sarahlcaffey** [AAVLD-USAHA-ITStandards/eCVI#14]
Do you guys think there should be a place for transportation fields like:

Transport Method: air, boat, car, truck, etc. (do you care?)

Interstate Transport? Y/N (this one we have as an optional field in mCVI... however, it should be pretty obvious based on the origin state and destination state whether the movement is intra vs. interstate). Given that, we will likely just remove this field altogether.

**Comment by sarahlcaffey** [comment]
As an update to you guys, we have decided internally to remove these two fields from the new version of mCVI.

**Comment by mkm1879** [comment]
Implemented as an optional element.  Will close without objection.

**Comment by mkm1879** [comment]
Closing pending full committee vote.
