### ISSUE TITLE
Custom Name/Value Pairs (optional)

### ISSUE THREAD

**Issue by nathanverrill** [AAVLD-USAHA-ITStandards/eCVI#15]
As discussed on the 4/4 working group call, consideration might be given to allowing custom name-value pairs that can be used to accommodate additional data that might be of use to industry or states in the future.

Counterpoint: 
Make sure it's clear that additional data should not confuse the standard and that it will be ignored by systems that are not expecting those fields, nor will it break the standard.

**Comment by mkm1879** [comment]
I added this in draft as an optional, repeating element MiscAttribute with two string attributes Name and Value.

<MiscAttribute Name="whatever" Value="25.2"/>  

Is there a better name?  Will this structure work?

**Comment by mkm1879** [comment]
These are implemented as suggested.  Will close soon without objection.

**Comment by mkm1879** [comment]
Closing pending full committee vote.

**Comment by mkm1879** [comment]
Closing pending full committee vote.
