### ISSUE TITLE
Embedded KML

### ISSUE THREAD

**Issue by nathanverrill** [AAVLD-USAHA-ITStandards/eCVI#19]
It might be of value to include an element specifically for a KML representation of the animal movement including the origin/destination placemarks and line connecting them.

The idea being the KML for the movement can be pulled directly from the CVI, without a system having to interpret that information first.

**Comment by mkm1879** [comment]
The Address does include GeoPoint (latitude and longitude).  I'm not convinced that converting to a KML Point would add much.

\<GeoPoint latitude=\"32.45678\" longitude=\"-82.98765"/\>
 
\<Point\>
      \<coordinates\>-122.0822035425683,37.42228990140251,0\</coordinates\>
    \</Point\>

**Comment by mkm1879** [comment]
Will close soon, if no further discussion.

**Comment by nathanverrill** [comment]
To provide more specificity, the idea is to include Placemarks in the schema for origin and destination, which will allow the origin and schema to easily be mapped in any system that accepts KML, without transforming the data. 

Format as follows:

```
  <Placemark>
    <name>Simple placemark</name>
    <description>Attached to the ground. Intelligently places itself 
       at the height of the underlying terrain.</description>
    <Point>
      <coordinates>-122.0822035425683,37.42228990140251,0</coordinates>
    </Point>
  </Placemark>
```

Google KML documentation: https://developers.google.com/kml/documentation/kml_tut#placemarks

A Path could also be included to connect the source and destination:

https://developers.google.com/kml/documentation/kml_tut#paths

**Comment by mkm1879** [comment]
I've drafted and pushed to GitHub a version with the coordinates in the Address type converted to KML format `<coordinates>` element.  I'm not sure how much this adds other than allowing copy to KML without reformatting. 

(The zero does not actually turn on intelligent altitude.  It means sea level.  It is ignored if the element  AltitudeMode is set to clampToGround (the default?).  Do we need to include the full Point element?  I would favor sticking to our data in either latitude and longitude or coordinate format.)

```
<Point id="ID">
  <!-- specific to Point -->
  <extrude>0</extrude>                        <!-- boolean -->
  <altitudeMode>clampToGround</altitudeMode>
        <!-- kml:altitudeModeEnum: clampToGround, relativeToGround, or absolute -->
        <!-- or, substitute gx:altitudeMode: clampToSeaFloor, relativeToSeaFloor -->
  <coordinates>...</coordinates>              <!-- lon,lat[,alt] -->
</Point>
```

**Comment by nathanverrill** [comment]
Hi @mkm1879 just realized that I didn't put the example code for the placemark in <> - hope that doesn't throw you for a whammy.

**Comment by mkm1879** [comment]
Suggest we have another brief discussion of structured lat/long versus single KML style string.  And then close based on majority opinion.  Neither is wrong.

**Comment by mkm1879** [comment]
Small group discussion settled on reverting to separate Latitude and Longitude attributes
