### ISSUE TITLE
Gratuitous element/attribute name changes

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#20]
I'm working on differencing the the two versions and cleaning up editing and formatting issues.  A few name changes may have caused more problem than help.

LicenseIssueState -> LicenseState
lat -> latitude
lng -> longitude

Are these worth keeping?  Or revert so it will be fewer changes?

others definitely (in my opinion) add clarity
idref -> AccessionRef (or BrandImageRef or AttachmentRef)

Please add a response if you find other clean-up I need to do.

**Comment by nathanverrill** [comment]
I like them spelled out, but I see the rationale and aligning names. I'm not super-familiar with XML, and I'm sure someone has encountered this before...

**Comment by mkm1879** [comment]
Will close soon, if no further discussion.

**Comment by mkm1879** [comment]
OK, really closing this time.
