### ISSUE TITLE
Test Code

### ISSUE THREAD

**Issue by sarahlcaffey** [AAVLD-USAHA-ITStandards/eCVI#21]
Wondering how the TestCode attribute is being used by others today. It is a required string field.

Suggestion from Dr. Martin: at a bare minimum, add a documentation element with a description of acceptable code systems.

**Comment by mkm1879** [comment]
It occurred to me that my program does use this field when it translates CO/KS eCVIs.  The only tests that are structured are Coggins and Brucellosis so following the field names in the XML data I used EIA and BRUC as the codes.  So I also kicked the can down the road.  Should we change this to an enumerated list of high level test "codes"?

**Comment by mkm1879** [comment]
Will leave as is and close without objection.

**Comment by mkm1879** [comment]
Closing
