### ISSUE TITLE
Area Statuses

### ISSUE THREAD

**Issue by sarahlcaffey** [AAVLD-USAHA-ITStandards/eCVI#22]
Suggestion below from Dr. Ellis to update some status elements:

Brucellosis status options be: Free or DSA (Designated Surveillance Area)
PRV  – not sure why they need to be in there at all any more; suggest removing

**Comment by mkm1879** [comment]
Any other changes needed in these lists?  (names and values for statuses)

If we don't hear any, will close.

**Comment by mkm1879** [comment]
The list of State Area or Zone status types has been reduced leaving all others to the other category.  Will close based on today's call.
