### ISSUE TITLE
eCVI Issuer/Source/Sender

### ISSUE THREAD

**Issue by MitzyTorres** [AAVLD-USAHA-ITStandards/eCVI#23]
Do we need an attribute for the CVI Issuer? (Ex: GVL, FortSupply, etc)?
How do we address paper CVIs from source/issuing state electronically messaging to the destination state?

**Comment by mkm1879** [comment]
I added an optional attribute for that.  It is just a string at this point.  Kicking the can down the road as to how to make sure that uniquely identifies the numbering sequence.  Being optional, I'm hoping it will future-proof that issue without interfering with immediate use without it.

**Comment by mkm1879** [comment]
Will close without objection.

**Comment by mkm1879** [comment]
Closing pending full committee vote.
