### ISSUE TITLE
Final Editing

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#26]
We inherited from version 1 a naming convention that does not follow most of the xml style guides out there.  In almost every system Elements are UpperCamelCase and attributes are lowerCamelCase.  That is, elements start with a capital and attributes with a lower case letter.

We have most all elements and most attributes with upper camel case.  Should we:

- change everything to conform with most of the XML world or,
- leave everything as is to minimize changes to implementation

**Comment by KimberlyTsao-USDA** [comment]
I'd vote for conforming to the standard conventions and can help with making the appropriate changes. Are there other potential time investments outside of this document we'd be forcing to fix this if we went with this decision? (If so, who should be weighing in?)

**Comment by dshipton** [comment]
As a company with an existing implementation - I'd much prefer to leave it alone. No tangible benefits to moving around capitalization that I can see.

**Comment by mkm1879** [comment]
To avoid confusion, will close this issue now and continue to conform to standards as much as possible without reopening any existing deviations.
