### ISSUE TITLE
Blank OtherOfficialID

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#30]
Just noticed that "" validates as a value for OtherOfficialID.  We probably should follow the NAHLN and define a NonBlankString type for this and other required string elements and attributes.

**Comment by alexturnerdvm** [comment]
This should be such that no one leaves it blank on purpose so that if it is blank, then it was a mistake rather than omitted to get around the system somehow.

**Comment by mkm1879** [comment]
We could copy the approach used by NAHLN for "NonNullString".  It requires at least one non-whitespace character.

**Comment by mkm1879** [comment]
Will add this solution to a draft in pending changes.
What other fields should be defined as NonNullString?

**Comment by YdaMitzyTorres** [comment]
This blank issue is on SpeciesOther as well

**Comment by mkm1879** [comment]
And ManagementID, EquineDescription, almost any required attribute now using xs:string.  Any exceptions?

**Comment by mmcgrath** [comment]
see https://github.com/AAVLD-USAHA-ITStandards/eCVI/commit/92fa9e5bbf525a3a4132068efa5f4f95c033b0ae for the proposed implementation

**Comment by mkm1879** [comment]
In Jan 2021 release v2.3
