### ISSUE TITLE
Email address restriction does not allow for in use top-level domains longer than 4 characters.

### ISSUE THREAD

**Issue by kkeuning** [AAVLD-USAHA-ITStandards/eCVI#33]
Opened pull request #32 to propose relaxing the email validation pattern to allow longer top-level domains.  We are aware of veterinarians with email addresses using longer generic top-level domains such as .auction that exceed the limit of the current validation pattern.

**Comment by mkm1879** [comment]
Before the standard was finalized I'd have made this change in a heartbeat.  I can't imagine even now that the change would "break" anything but need to be careful.

**Comment by mmcgrath** [comment]
I agree this is backwards compatible and won't break anything - when the schema is updated on github we will "upgrade" it in StateVet and CVI Central to make sure any new documents with these unusual email addresses are accepted.

**Comment by mkm1879** [comment]
Unless we receive negative responses, this will be implemented in version 2.0.1 released on February 1, 2019.

**Comment by mkm1879** [comment]
This was resolved with release 2.0.1
