### ISSUE TITLE
Address vs. Address Block

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#35]
Having two different formats is causing more problems than it is solving.  While the address of consignor, consignee, shipper, and veterinarian are not the key physical addresses, it is still easier to deal with one format rather than two.

**Comment by alexturnerdvm** [comment]
I think that all address blocks should be identical to the "separated" version that we currently have for the animal location, so that each of these blocks will send the information in a similar format rather than a single text block.

**Comment by Deevet84** [comment]
This issue needs to be expedited quicker than the normal schema working group process please. It needs to just be corrected as we discussed and outlined above as a "fix" to the new eCVI v2 schema code rather than getting NASAHO approval as a new idea. It is affecting USA Herds users every day. Thanks.

**Comment by mkm1879** [comment]
I have made the suggested change and pushed to the pendingChanges branch.  Please evaluate.

Personally, I have software in Alpha test stage.  Doing this sooner will be much better for me than doing it later, but my needs are trivial.

**Comment by Deevet84** [comment]
What is a pending changes branch?

**Comment by mkm1879** [comment]
The official release in the "master" branch hasn't changed but I wanted folks to be able to look at changes I suggest we make.  Those are in pendingChanges.  See the Branch button at the top of the Code tab in GitHub.

**Comment by SusanCulp** [comment]
https://github.com/AAVLD-USAHA-ITStandards/eCVI/tree/pendingChanges


Susan Culp, DVM
Veterinarian
Institute for Infectious Animal Diseases (IIAD)
A Member of the Texas A&M University System

1500 Research Parkway, Suite B270
College Station, TX 77843-2129
Office 979.458.2375 | Fax 979.845.6574
iiad.tamu.edu<http://iiad.tamu.edu> | @IIADnews
TEXAS A&M UNIVERSITY | FEARLESS on Every Front

**Comment by mmcgrath** [comment]
I am happy with the proposed change - we can accommodate the change with a week's notice of it being adopted by those generating/sending eCVIs.

**Comment by mkm1879** [comment]
Implementation complete in v2.1
