### ISSUE TITLE
Sovereign Tribal Nations Support

### ISSUE THREAD

**Issue by NatePlumm-USDA** [AAVLD-USAHA-ITStandards/eCVI#37]
It appears that the current eCVI schema does not allow for a Sovereign Tribal Nation to be captured anywhere. A Tribal Nation could be part of any address contained with the eCVI (e.g. Veterinarian, Origin, Destination, Consignor, Consignee).

One possible simple fix is that anywhere that a US State is captured, also allow entry of a Sovereign Tribal Nation. When a value exists in the new Sovereign Tribal Nation field, then the address should be interpreted to geographically fall within the state listed but not necessarily politically or jurisdictionally.

I am not certain how many Tribal Nations there are. I suspect there are dozens or maybe even hundreds. I am also not certain how often the list changes. As such, further research is required to know if using an Enum is the best approach for such a list as opposed to free text entry.

**Comment by mkm1879** [comment]
An enumeration would be much more automated.  But maybe the mere existence of text in that attribute would trigger manual processing.

**Comment by NatePlumm-USDA** [comment]
One of the challenges USDA has is related to message routing based on state, tribal nation and other values found in the XML. An enumeration as opposed to free text is definitely preferable if we can do it that way.

**Comment by StaceySchwabenlander** [comment]
As I mentioned on the call today, I wonder if, before any modifications take place in the standard, there needs to be a larger discussion (at the level of NASAHO and any similar group that represents all Tribal Nations) to determine whether the eCVIs we are discussing that use the XML standard within states are accepted by the Tribal Nations for movement of animals leaving or entering tribal lands.

**Comment by SusanCulpDVM** [comment]
This issue was discussed at the November 30, 2022 meeting of the eCVI Data Standards Workgroup.  Since this is outside of the scope of this Workgroup, the consensus was to close this issue and refer it to the NASAHO eCVI Approval Committee.
