### ISSUE TITLE
Total number in consignment

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#38]
Dr. Ellis (AgView) has received requests to include the total number of animals in the consignment as a distinct field in the data file.  

My view is that this is simply the total of the number of animals in groupLot(s) plus the count of individual animal records.  However including as a separate field would simplify some logic and might also serve as an internal check value.

Allowing multiple species complicates this.  Would it actually be # per species?

**Comment by ryanscholzdvm** [comment]
We encountered this issue with an eCVI which allowed the vet to manually record the total number of animals on the CVI, and they recorded 46 animals, but then rather than add the animals as group lots, they added them as individual animals with the head count in the ID field. When it was imported from the XML, it imported with only 3 animals. We currently review all eCVIs from this system manually, but having this field in the data file would have allowed us to catch this issue programatically.

**Comment by StaceySchwabenlander** [comment]
I'm not sure if this is the reason behind this issue, but here is a way I see this would impact veterinarians.
-We have an out of state market we deal with that inspections (for example) 500 dairy steers. The veterinarian may record the same official IDs for all 500 dairy steers on several CVIs. This means there are 500 individual animals on each CVI. Then, each CVI is issued to a different destination, where the animals shipped field indicates how many of the 500 shipped (but not which of the 500). Total shipped may be 300, 50, 50, 100.

Considerations: preventing this - having the animal shipped field be calculated from the individual animals + group animals would stop the behavior described above (ideally we want to know which head shipped, but for animals not requiring IDs to be documented, we are getting more than is required). The result would be the individual animal IDs are either 1) replaced by a statement that all cattle are officially ID'ed IF that is acceptable to the state of destination and no official IDs are received at all, or 2) the veterinarian adds the actual number shipped into a random field such as the statement field.

Just some thoughts on this issue. Perhaps knowing how the issue originated would clarify if this is truly a policy issue or not.

**Comment by SusanCulp** [comment]
@StaceySchwabenlander, after some investigation on my side, I believe this original inquiry came from an AgView CVI SAHO customer experiencing difficulties with group movement as it was originally implemented in the AgView system.  The request was for the schema to display a field for "total number of animals in consignment".  Doing so would be duplication in the schema as the data is already there.  As such, I believe the subcommittee may want to consider closing this issue as originally submitted on the April 13th call.

**Comment by mkm1879** [comment]
This change was voted down by the committee at its 09/18/2020 meeting.
