### ISSUE TITLE
Canadian and Mexican RFID AnimalTagType(s)

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#39]
Even with our scope being interstate we could still see these tags.  I guess we should have a type for them.  (124 and 484 prefixes I think.)

**Comment by StaceySchwabenlander** [comment]
I agree that country/territory prefixes representing official tags in those countries/territories, should also be able to be accurately captured. MN's AIN regular expression is: ^(?!999)((840)|(124)|(484)|(9[0-9]{2}))[0-9]{12}$. Can these also be captured as AIN, or would they need to be an alternate tag type?

**Comment by jconlon** [comment]
Agree with Stacey on the regex.  Should we just change the simpleType name="AINType" regex pattern to the one she presented?

**Comment by mkm1879** [comment]
Currently 124 and 484 are listed in MfrRFID rather than AIN.  But they aren't manufacturer codes they are different country codes.  But they still aren't AINs as defined in the traceability rule.

> § 86.1 Definitions.
Animal identification number (AIN).
A numbering system for the official
identification of individual animals in
the United States that provides a
nationally unique identification number
for each animal. The AIN consists of 15
digits, with the first 3 being the country
code (840 for the United States or a
unique country code for any U.S.
territory that has such a code and elects
to use it in place of the 840 code). The
alpha characters USA or the numeric
code assigned to the manufacturer of the
identification device by the
International Committee on Animal
Recording may be used as an alternative
to the 840 or other prefix representing
a U.S. territory; however, only the AIN
beginning with the 840 or other prefix
representing a U.S. territory will be
recognized as official for use on AIN
tags applied to animals on or after
March 11, 2015. The AIN beginning
with the 840 prefix may not be applied
to animals known to have been born
outside the United States.

Should I put in both places?

**Comment by StaceySchwabenlander** [comment]
Good question. I know I had documentation from USDA that indicated that country of origin prefixes (eg 124, 484) for RFID tags would be recognized as official in the US, but I'm struggling with finding that in writing as I look now. Clearly that got missed in the ADT rule as re-reading it now, country of origin tags outside the US are not included as AIN tags, as you indicated Mike. Perhaps having it in both places would be ok if that doesn't mess up how the data is transmitted? Would there be any issues with a system having issues matching a tag type if two types fit? In our system in MN, we capture 124 tags as AIN tags, but I'm not sure what other SAHO offices do.

**Comment by geisersu** [comment]
In looking at the regex for identification in the schema we have some concerns. As you note MfrRFID includes 124 and 484 in the regex and these should be in AIN as Canadian and Mexican official RFID and official visual/RFID respectively.  The US territory prefixes need to be captured/supported as well.  In addition, the NUES9 only contains postal codes for a few States where all States may use their postal code, so I’m not sure why only a few are highlighted.  We are mapping schema ID to VSPS and want to make sure they are captured appropriately.

**Comment by mkm1879** [comment]
I can shed a little light on the NUES9 regex.  I believe we heard that the state territory codes listed were the only ones that used that instead of the numeric codes.  If that is incorrect, we should revisit.  The fewer patterns the better to avoid accidental collisions.

**Comment by NatePlumm-USDA** [comment]
I believe there are a few ways to approach these regex related issues. Depending on this eCVI standard's goals, I do not know which is more appropriate.

One approach, and one that appears to currently be the case, we maintain this schema in a manner consistent with a living document. In this scenario these regexes are maintained to reflect expected values. For example, if only 8 countries produce and use country prefixed RFID numbers then the regex would show those 8 countries. In the case of a NUES tag, the prefixes would be limited to those known to be in use or available for use.

An alternative approach is to allow for current and known values as well as those that could reasonably be valid in the future. In this scenario the regexes would contain the comprehensive set of values that are known today and not unreasonable  to expect at a later date. For example, NUES tag prefixes would allow for all state numeric and alpha prefixes (e.g. MI and 34) and country prefixed RFID numbers would include all valid country codes.

The cons of the first approach is each time a state or country utilizes new tag prefixes (consistent with standards) an updated schema must be applied to every participating system. Additionally each time a discrepancy is discovered between expected and actual values being used the same update and distribution must be made. For any system behind on the schema there is the potential for manual intervention being required and possibly data loss if data is rejected.

The cons of the second approach is a value may end up being included that does not actually exist today. For example, if North Dakota does not use the ND tag prefix on NUES tags it could still validate. In the case of AIN/RFID tags, countries that currently do not use the country prefixed tagging system may validate in the same way. 

A method for mitigating the second approach that USDA applies elsewhere is to have a secondary schema based on the standard that is more restrictive which does not reject data but instead causes it to be flagged for quality control. I would be happy to elaborate on this method should anyone be interested.

For anyone curious, this (untested) regex shows how large a regex could be that just limits AIN/RFID based on country codes.

^((004)|(008)|(010)|(012)|(016)|(020)|(024)|(028)|(031)|(032)|(036)|(040)|(044)|(048)|(050)|(051)|(052)|(056)|(060)|(064)|(068)|(070)|(072)|(074)|(076)|(084)|(086)|(090)|(092)|(096)|(100)|(104)|(108)|(112)|(116)|(120)|(124)|(132)|(136)|(140)|(144)|(148)|(152)|(156)|(158)|(162)|(166)|(170)|(174)|(175)|(178)|(180)|(184)|(188)|(191)|(192)|(196)|(203)|(204)|(208)|(212)|(214)|(218)|(222)|(226)|(231)|(232)|(233)|(234)|(238)|(239)|(242)|(246)|(248)|(250)|(254)|(258)|(260)|(262)|(266)|(268)|(270)|(275)|(276)|(288)|(292)|(296)|(300)|(304)|(308)|(312)|(316)|(320)|(324)|(328)|(332)|(334)|(336)|(340)|(344)|(348)|(352)|(356)|(360)|(364)|(368)|(372)|(376)|(380)|(384)|(388)|(392)|(398)|(400)|(404)|(408)|(410)|(414)|(417)|(418)|(422)|(426)|(428)|(430)|(434)|(438)|(440)|(442)|(446)|(450)|(454)|(458)|(462)|(466)|(470)|(474)|(478)|(480)|(484)|(492)|(496)|(498)|(499)|(500)|(504)|(508)|(512)|(516)|(520)|(524)|(528)|(531)|(533)|(534)|(535)|(540)|(548)|(554)|(558)|(562)|(566)|(570)|(574)|(578)|(580)|(581)|(583)|(584)|(585)|(586)|(591)|(598)|(600)|(604)|(608)|(612)|(616)|(620)|(624)|(626)|(630)|(634)|(638)|(642)|(643)|(646)|(652)|(654)|(659)|(660)|(662)|(663)|(666)|(670)|(674)|(678)|(682)|(686)|(688)|(690)|(694)|(702)|(703)|(704)|(705)|(706)|(710)|(716)|(724)|(728)|(729)|(732)|(740)|(744)|(748)|(752)|(756)|(760)|(762)|(764)|(768)|(772)|(776)|(780)|(784)|(788)|(792)|(795)|(796)|(798)|(800)|(804)|(807)|(818)|(826)|(831)|(832)|(833)|(834)|(840)|(850)|(854)|(858)|(860)|(862)|(876)|(882)|(887)|(894))\d{12}$

**Comment by StaceySchwabenlander** [comment]
@NatePlumm-USDA - you do a nice job outlining the options. I'm not certain what the right choice is. 

For AIN tags, it seems more likely a possibility of prefixes being added over time considering that AIN RFID tags are the planned tags for the future. If less changes to the schema/tag reg exes are desirable, including country codes and territory codes in the reg ex seems like a possible solution.

Perhaps the same argument isn't the case for NUES9 tags. If these tags are to be phased out in the near future, it seems less likely that additional states will elect to begin printing NUES9 tags with their postal codes. The reg ex we use in MN for NUES9 tags is this: ^([0-9]{2}|IA|MD|MN|NM|NY|US|WA|WY)[A-Z]{3}[0-9]{4}$

MN is included in the reg ex because the USDA has approved a small NUES9 tags for use in swine that is printed with MN in place of the 41. These tags are not used in cattle/bison.

**Comment by mkm1879** [comment]
A question was asked about where these Regexs are found in the GitHub site.  They are in the schema itself, of course.  But take some doing to find.

The NUES9 Regex can be found at [Line 967](https://github.com/AAVLD-USAHA-ITStandards/eCVI/blob/bc38c5df6d67e2583b71814e99ab50259cf454dd/ecvi2.xsd#L962)  The other tag type regexs are all nearby.

**Comment by StaceySchwabenlander** [comment]
Thanks @mkm1879 - It looks like the NUES9 regex is missing IA and WA, but otherwise matches what we have here in MN.

**Comment by mkm1879** [comment]
I guess we can generalize this to a question of whether we want the standard to guide the use of identifiers that we actually see "in the wild" or if it should try to capture everything that could possibly be "legal."  I just noticed that the 2019 [ADT standards document](https://www.aphis.usda.gov/traceability/downloads/ADT_standards.pdf) shows US Territories country code prefixes as valid in AIN RFIDs.  So, even if we didn't use Nate's list of all country codes and restricted to US, we would need the territories.  That is if we elect to try to cover every combination without resort to "OtherOfficialID".  

I would suggest we all look at use-cases.  How do we envision anyone actually using the labels applied to the AnimalTag element?  If complicated enough, would the receiving system not just apply their own classification logic rather than relying on the label?

**Comment by SusanCulp** [comment]
Email from Dr. Turner on Friday, September 18, 2020:

Susan, on the line of commits for Canada IDs, their ISO country code is 124, not 123.
Alex
 
Alex K. Turner, DVM
Assistant Director, National Animal Disease Traceability & Veterinary Accreditation Center
USDA APHIS VS Strategy & Policy
2150 Centre Avenue, Building B
Mailstop 3E86, Room 3E100
Fort Collins, CO 80526
Office: 970.494.7353
Mobile: 970.556.3568

**Comment by mkm1879** [comment]
In Jan 2021 release v2.3
