### ISSUE TITLE
EECVI Reference Implementation

### ISSUE THREAD

**Issue by DavidZiemann** [AAVLD-USAHA-ITStandards/eCVI#40]
## EECVI Reference Implementation
After reviewing the current CVI data standard, I produced a reference implementation of a proposed EECVI data standard which attempts to use as much of the current CVI standard as possible. I have included a very basic PDF documenting the new XML schema. You can view that document below. I have also developed the XML schema definition along with an example XML file to validate against the schema. Currently, I am unable to submit a pull request to this repository to present those files. 

#### [eecvi-documentation.pdf](https://github.com/AAVLD-USAHA-ITStandards/eCVI/files/3522465/eecvi-documentation.pdf)

While much of the information is the same as the current CVI standard, there are a few core differences I would like to point out to the committee for review. It is possible to conform the EECVI data to the CVI XML standard, but an EECVI is not generated, signed, or used in the same way as a traditional CVI.

### Official ID is a new required field that is not available in the current CVI schema
This official ID is restricted to one of four different options. These options could be on the animal or completely separate (Not included on a traditional CVI). For this reason, I chose to make this a separate data point that can be easily retrieved.
- Lifetime Brand Inspection Number
- Photo EIA
- Microchip
- EIA Accession Number
### Qualifying EIA/Coggins test is a required field for an EECVI
A qualifying EIA/Coggins test is required for a valid EECVI & includes parameters that are not available on a CVI test. The additional fields necessary are:
- Blood Drawn Date
- Issue Date
- Lab Name
- Document Number (EIA/Coggins test ID)
### Owner, Origin, and Destination are required for an EECVI
The current CVI standard does not require an owner. This is a situation where the CVI standard is less restrictive than the EECVI data standard.
### Species code is fixed to `EQU`
This is more restrictive than the current CVI standard.
### Movement Purpose is more restrictive than current CVI schema
The current EECVI standard limits movement purpose to the following which is more restrictive than the current CVI standard:
- Grazing
- Medical
- Treatment
- Race
- Rodeo
- Show/Exhibition
- Pleasure
- Training
- Work

## A final note regarding data standards

Ultimately, my concern with using the CVI schema is that we would not be able to accurately distinguish between the two different document types for traceability and reporting. Additionally, if the two document types diverge in the future, there will not be an easy way to separate the formats. I see a huge opportunity within this group to provide data standards for CVIs, EECVIs, Equine Coggins Tests (EIAs), and any future documents. My concern is that by trying to use one schema for all document types, we will cause more issues in the future for the committee and anyone who will want to conform to this standard.

**Comment by DavidZiemann** [comment]
I have generated the logic to import EECVIs according the current v2 data standard. Here is the output XML for reference:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<cvi:eCVI xmlns:cvi="http://www.usaha.org/xmlns/ecvi2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" CviNumber="FAKE-EG-19-IA-2687-001" ExpirationDate="2020-03-08" IssueDate="2019-09-09">
    <cvi:Veterinarian LicenseState="TX" LicenseNumber="" NationalAccreditationNumber="054897">
        <cvi:Person>
            <cvi:Name>Jesse Golfer</cvi:Name>
        </cvi:Person>
        <cvi:AddressBlock>123 Golfer St/nAmes, IA, 12345</cvi:AddressBlock>
    </cvi:Veterinarian>
    <cvi:MovementPurposes>
        <cvi:MovementPurpose>Racing</cvi:MovementPurpose>
    </cvi:MovementPurposes>
    <cvi:Origin>
        <cvi:PremName/>
        <cvi:Address>
            <cvi:Line1>123 Fake Drive</cvi:Line1>
            <cvi:Town>Laredo</cvi:Town>
            <cvi:State>TX</cvi:State>
            <cvi:ZIP>30192</cvi:ZIP>
        </cvi:Address>
        <cvi:Person>
            <cvi:Name>TX Test Address</cvi:Name>
            <cvi:Phone Number="1234567890" Type="Unknown"/>
        </cvi:Person>
    </cvi:Origin>
    <cvi:Destination>
        <cvi:PremName/>
        <cvi:Address>
            <cvi:Line1>123 Fake Street</cvi:Line1>
            <cvi:Town>Ames</cvi:Town>
            <cvi:State>IA</cvi:State>
            <cvi:ZIP>50010</cvi:ZIP>
        </cvi:Address>
        <cvi:Person>
            <cvi:Name>IA Test Address</cvi:Name>
            <cvi:Phone Number="1234567890" Type="Unknown"/>
        </cvi:Person>
    </cvi:Destination>
    <cvi:Animal InspectionDate="2019-09-09" Breed="AD" Sex="Female" Age="2014-09-07">
        <cvi:SpeciesCode Code="EQU" Text="Equine"/>
        <cvi:AnimalTags>
            <cvi:OtherOfficialID Type="OTHER" Number="LBI-12345"/>
            <cvi:OtherOfficialID Type="NAME" Number="Animal 16"/>
            <cvi:EquineDescription Description="Document{{otherMarkings=, leftHindMarkings=markings, headMarkings=Not, rightForeMarkings=real, rightHindMarkings=Sock, leftForeMarkings=the}}"/>
            <cvi:OtherOfficialID Type="OTHER" Number="303"/>
        </cvi:AnimalTags>
    </cvi:Animal>
    <cvi:MiscAttribute Name="Type" Value="EECVI"/>
    <cvi:MiscAttribute Name="OfficialIdType" Value="lifetimeBrandInspection"/>
    <cvi:MiscAttribute Name="LifetimeBrandInspectionDate" Value="2019-09-03"/>
    <cvi:MiscAttribute Name="LifetimeBrandInspectionState" Value="IA"/>
    <cvi:MiscAttribute Name="LifetimeBrandInspectionNumber" Value="LBI-12345"/>
</cvi:eCVI>
```

There are a few items to note regarding using this XML:
- The official ID is not properly represented in the animal block due to the constraints of the current schema. I have included the proper type and value in the `MiscAttribute` fields.
- The official ID types we utilize are `Microchip`, `Photo EIA`, `EIA Accession Number`, and `Lifetime Brand Inspection`.
- Animal inspection date is not required on the current EECVI permit approval process, so I set it to the date of issuance.
- Added a `MiscAttribute` to CVIs and EECVIs to differentiate types.

As always, I appreciate and welcome any feedback.

**Comment by mkm1879** [comment]
I question whether "Animal 16" or "303" are official ID, I would think they belong in ManagementID.  We don't have a good way of enforcing that with schema language.  
I could certainly see proposing a structured Lifetime Brand Inspection ID type, assuming there is sufficient commonality among all the brand states.  
ps. Clever use of embedded JSON snippet and correct, in my opinion, use of the Miscellaneous Attribute element.
Oh and this is 2.1.  2.2 is out with the structured Address everywhere.

**Comment by DavidZiemann** [comment]
@mkm1879 the animal name and ID are currently being included for all of our CVIs if there is not another ID type that follows the current schema definition. I agree that it is not a great use of the official ID attribute. I will move the GVL ID over to `ManagementID`.

Also, I will update our schema to the latest while the code is fresh in my mind.

If this format looks like it works for everyone, it should be live tomorrow evening for use.

**Comment by mkm1879** [comment]
Many of the issues raised here warrant revisiting on their own, but in the current content of the eeCVI this issue is closed.
