### ISSUE TITLE
Age does not allow fractional years

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#45]
One implementation has tried sending age as, for example, "2.5a".  This does not validate against the current schema which only allows integers.  Translating to months such as "30mo" works but implies more precision than the vet meant to record.  

Should the definition of age be changed to allow decimals rather than just integers?

**Comment by mmcgrath** [comment]
Trace First could easily accommodate this amendment if it was implemented.

**Comment by StaceySchwabenlander** [comment]
Provided this isn't an onerous change, it seems this may be desirable for accredited veterinarians, as you mention @mkm1879 - when a veterinarian is estimating an age and doesn't want to imply a high degree of precision. We'll need to continue to ensure clarity on what the number refers to (days, weeks, months, years) but I presume that wouldn't be impacted by a change only to allowing an decimal place vs an integer.

**Comment by mkm1879** [comment]
In Jan 2021 release v2.3
