### ISSUE TITLE
Consider Semantic Versioning

### ISSUE THREAD

**Issue by jconlon** [AAVLD-USAHA-ITStandards/eCVI#47]
Since we have vendor and state implementations that send and receive our xml instances.  Consider adopting a Semantic Versioning Approach. See: [Semantic Versioning](https://semver.org/)  

If the implementation developers are aware of how we are changing our schema they can better adopt code to handle patch and minor changes without breaking.

Along with that to better identify our changes we may want to add the following tags (and labels):

- MAJOR
- MINOR
- PATCH

**Comment by mkm1879** [comment]
Are we not doing this other than we haven't needed patch releases?
