### ISSUE TITLE
Provide Movement Information for International Destinations

### ISSUE THREAD

**Issue by DavidZiemann** [AAVLD-USAHA-ITStandards/eCVI#48]
## What is happening?
Currently, any movement out of the US is not valid against the schema. In order to provide better support for international movement, I would like to propose an incremental change to the `Address` validation to support these non-USA locations. It is vital to note this is **only for international destinations** and no data will be exchanged with international governments at this time. The goal is to provide better clarity into what animal movements are happening to international destinations. It is still vital that the veterinarians go through the USDA for any international movement.

## Proposed Solution
The following XML would be a new complex type that we can use if the address is not within the USA. I referenced a number of existing XSD formats to ensure we can comply with our current format while also looking towards the next major update to the schema.

```xml
<xs:element name="internationalAddress">
    <xs:annotation>
        <xs:documentation>Address that is not within the USA. This address is less restrictive than addresses identified within the United States.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
        <xs:sequence>
            <xs:element name="addressLine1" type="xs:string" minOccurs="1"/>
            <xs:element name="addressLine2" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="city" type="xs:string" minOccurs="1"/>
            <xs:element name="state" type="xs:string" minOccurs="1"/>
            <xs:element name="country" type="xs:string" minOccurs="1"/>
            <xs:element name="postalCode" type="xs:string" minOccurs="1"/>
            <xs:element name="GeoPoint" minOccurs="0" maxOccurs="1"/>
                <xs:annotation>
                    <xs:documentation>Simple Latitude and Longitude in decimal degrees.</xs:documentation>
                </xs:annotation>
                <xs:complexType>
                    <xs:attribute name="Latitude" type="LatitudeType" use="required"/>
                    <xs:attribute name="Longitude" type="LongitudeType" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
```

Then, we can use the following within the `PremType` field to allow for international countries to be set. By using a `choice`, we will not impact any current implementations of the XML format, but provide a path for having more accurate data for anyone who works with international movement. 

```xml
<xs:choice>
    <xs:element ref="Address" minOccurs="1" maxOccurs="1"/>
    <xs:element ref="ForeignAddress" minOccurs="1" maxOccurs="1"/>
<xs:choice>
```

## Implications
While this is not a breaking change, it will require work by vendors to be able to read the new complex type.

## Long Term Solution
It is worth noting that a long term solution would most likely include a country code that conforms to the [ISO 3166 standard](https://www.iso.org/iso-3166-country-codes.html). There are a number of XSD implementations available for this standard which could help shorten the time to develop the updated address standard. I would also be open to a standardization of our `Address`, `PremType`, and `ContactType` implementations to simplify some of the differences between these types, but that is most likely a ways down the road.

**Comment by geisersu** [comment]
APHIS does not support the inclusion of international destinations in the eCVI schema.  When pets are moving interstate, there should not be an international address involved so this data is not relevant for eCVIs.  Export certificate endorsement and export reporting falls under APHIS’s authority; this data is already generated internally and available. The only IT system currently approved and used to generate export certificates for the international movement of live animals is Veterinary Export Health Certification System (VEHCS).  In addition, although the intended goal is to provide better clarity into what animal movements are happening to international destinations, there is no guarantee that the export would be endorsed by APHIS.

**Comment by StaceySchwabenlander** [comment]
I think requesting the XML subcommittee consider changing the schema to allow for international destinations would be a policy issue to be considered by the National Assembly. Since international movement is under the purview of the USDA, the NA would need to consider whether this is something they would want the subcommittee to pursue.

**Comment by dlkdvmphd** [comment]
Not trying to complicate matters, but we have found that many of these CVIs are being issued to fulfill airline requirements.  At least in some cases, the vets are completing the international paperwork with USDA and country of destination plus they are completing a Interstate CVI ]that is being submitted to state of origin (automatically if it is an electronic CVI)] that is used for the airlines.

**Comment by VSsrydberg** [comment]
We have had several requests from DVMs to use eCVIs for international travel.  Canada, for instance, requires a certificate signed by a DVM for the animal. It is not being used to bypass the USDA VEHC system in place.  Collecting data on these might be informative.

**Comment by StaceySchwabenlander** [comment]
I don't think there is a problem with allowing eCVIs to be used for international destinations @VSsrydberg - provided that eCVI meets all federal and international destination requirements and standards. However, I think it is outside of the scope of this subcommittee to write the schema to include international destinations UNLESS the parent committee were to approve that AND the National Assembly supported this. Just my two cents!

**Comment by VSsrydberg** [comment]
Stacey,

Sound logic!

Scott Rydberg
Owner
River City Data/VetSentry
320-334-2875
www.rivercitydata.com<http://www.rivercitydata.com/>
www.vet-sentry.com<http://www.vet-sentry.com/>

[River City Dada]

[cid:image002.jpg@01D68DB9.F4C0A3A0]

**Comment by SusanCulpDVM** [comment]
This issue was discussed at the November 30, 2022 meeting of the eCVI Data Standards Workgroup.  Since this is outside of the scope of this Workgroup, the consensus was to close this issue and refer it to the NASAHO eCVI Approval Committee.
