### ISSUE TITLE
Include Disease name/code alongside Test Code in Test element

### ISSUE THREAD

**Issue by jbartlettUSDA** [AAVLD-USAHA-ITStandards/eCVI#49]
The test code alone isn't sufficient to describe what disease each test is being performed for.  Could the Test element be updated to include the disease name or an equivalent well-defined code as well?

**Comment by mkm1879** [comment]
I would agree.  We kind of swept the whole test code thing under the rug before.  Left it TBD.  I'd, of course, like us to use LOINC codes.  Then the code would be enough to do everything.  But that might be a heavy lift for most of our implementers.

[LOINC ](https://loinc.org)by the way stands for Logical Observation Identifiers Names and Codes.  It is the international standard for naming specific laboratory tests as well as many clinical observations.  It is what the National Animal Health Lab Network uses to identify tests.  We actually could enumerate the LOINC codes for commonly required tests.  That might be overkill.  

My, slightly snarky, point was that it is non-trivial to make a list of all possible tests that would be universal and non-ambiguous.

**Comment by ryanscholzdvm** [comment]
This is something that we should probably revisit. In re-reading the original issue, I am not convinced that it was resolved. I would tend to agree with the comment by @mkm1879, except to add that it may not be necessary to include every possible disease/test out there. Similar to how we handle a number of enumerated lists (species, movement purpose, etc), I think that we could probably modify the Test element to include a choice of either an enumerated "TestType" (either just a test type, or a combination of disease with the type of test), or an "TestTypeOther" that allows free-text entry. This would likely look very similar to how species is handled as either Species or SpeciesOther. 

I think that the benefits of doing this are probably fairly self-evident, but the two biggest issues that I would see are developing the list of "usual" tests, and this change would be a relatively significant change as it would change the test type from a free-test attribute (TestCode, TestName) to an element. 

Going this route may also make the test element simpler to understand. If we define the disease separate form the test type, it allows more flexibility to include most disease/test combos without having to include every single combo in a single (giant) list (Disease=EIA Test=ELISA, Disease=EIA, Type=AGID, Disease=Avian Influenza, Type=AGID, etc)

**Comment by mkm1879** [comment]
Add a few more attributes and you would have LOINC codes! Seriously, if we are trying to get this field unambiguous, we shouldn't reinvent the wheel. Bret and Letitia at Iowa State have mapped LOINC codes for just about any test that could be required on a CVI. We could enumerate and then leave something for "other" when a new test requirement comes along.

**Comment by ryanscholzdvm** [comment]
I took a stab at starting a list of at least diseases that we see in our eCVI system. It is by no means exhaustive, and I didn't try to cover all of the test types, but hopefully it will spur some additional discussion.
- Equine Infectious Anemia Virus
- Brucella abortus
- Brucella ovis
- Brucella suis
- Pseudorabies
- Tuberculosis
- Tritrichomonas foetus
- Caseous lymphadenitis
- Caprine Arthritis and Encephalitis
- Bovine Viral Diarrhea Virus
- Rabies titer
- Avian Influenza
- Salmonella pullorum

**Comment by mkm1879** [comment]
To LOINC code these, I will need the test type (PCR, ELISA, AGID, etc.) as well as specimen type if not obvious. For serology, it is looking at antigen or antibody. I can try to guess from my admittedly limited experience but better to be explicit as you find them.  

Thanks

**Comment by ryanscholzdvm** [comment]
I wonder if LOINC may be more detail than we necessarily need in most situations? Im concerned that to provide a list of potential LOINC codes for likely tests it may become a very long list very quickly, and requires information that we don't generally require on a CVI. Just for Avian Influenza, you potentially have a long list:

AI PCR - Oropharyngeal swab
AI PCR - Oropharyngeal pool
AI PCR - Tracheal swab
AI PCR - Tracheal pool
AI PCR - Cloacal swab
AI PCR - Cloacal pool
AI ELISA - Serum
AI ELISA - Whole Blood
AI AGID - Serum
AI ELISA - Whole Blood

What if we gave an option (like we do in several other places) to either specify a LOINC code, or specify a disease and test type from defined lists, with a third free-text "Other" option. For an integrated platform that is transferring information from a lab submission to a CVI, the LOINC would be really easy to transfer over (we probably wouldn't even need to create a list), but for situations where the vet is entering the lab results manually, they could select from a defined list of common diseases, and then a defined list of common test types. From the database side consuming the data, I think that either one of those would be fairly easy to work with, and from the SAHO side, either one of those would get us the information that we are looking for.

**Comment by mkm1879** [comment]
It is certainly possible that LOINC will have more or less specificity than we want/need. The committee tries really hard to make different codes when and only when there are **clinically important** differences. All those AIs would be the same code as would an AB ELISA whether serum or whole blood is submitted.

If we find any really bad mis-fits, I can request new codes...and use temporary codes or the best we have in the meantime.

**Comment by SusanCulpDVM** [comment]
Included in Release Version 3.0 Update.  Discussed with eCVI Workgroup on January 24, 2024.  All agreed to resolve and close this issue.
