### ISSUE TITLE
Material that travel with CVIs that are not live animals (semen, eggs, etc.)

### ISSUE THREAD

**Issue by SusanCulp** [AAVLD-USAHA-ITStandards/eCVI#50]
Separating this issue out from "Ongoing Species List Refinement - Issue #8" as a new issue here.

New issue to address how to handle material that travel with CVIs that are not live animals (semen, eggs, etc.)

**Comment by StaceySchwabenlander** [comment]
I continue to support the option to allow for a field to capture/clarify when non-animals (semen, embryos, etc) are moved on CVIs. It would be important to continue to capture the species of non-animals moved as well as the type of non-animal.

**Comment by CAllenMN** [comment]
I also support an option to have a specific field to capture non-animals on CVIs.  Having this distinction would greatly reduce the time it takes to process these documents as it would allow processing tools a way to auto-route them, as a distinct subset of CVIs within a species/ type, as needed by agencies.

**Comment by ryanscholzdvm** [comment]
This may be complicating it unecessarilly, but at this point, we have Animals and GroupLots in the Schema. Semen/Eggs/etc are not animals and they are not group lots. The solution to this may require a third element type (i.e. Item) with it's own unique data elements. This may be the easiest way to clearly identify that while the semen is from beef cattle, it is not in fact a bull (you will likely still have a species, but not sex/age), and to avoid some of the issues with currently required fields such as sex under Animal and GroupLot.

**Comment by mkm1879** [comment]
I agree.  I think an element with a name something like "Product" and an enumerated attribute like "ProductType" along with the needed elements would make the most sense.  Complicates the schema a little but actually simplifies the instance documents.

This isn't one I'm going to be able to just throw up a suggested edit.  We need group input.

**Comment by ryanscholzdvm** [comment]
I would propose an element Product that closely mirrors the GroupLot element
**Attributes:**
-ProductType (enumerated list)
-Quantity
-Unit
-Breed (this may not actually be needed)
-Description

**Child Elements**
-Either: SpeciesCode/SpeciesOther
-ProductID
-[Test]
-[Vaccination]
I don't know if any of these products (or the source animals) would be requiring tests or vaccinations, so those two may not be necessary.

We don't require CVIs for animal products, so I don't know that I have enough experience with this topic to take as stab at what the products would be. I think that all of the other attributes/child elements would likely follow the same formats that are already defined in the standard

**Comment by StaceySchwabenlander** [comment]
I like the option of being able to capture a product and product type (with any needed associated fields). MN also doesn't require CVIs for semen and other products (I can only speak for mammals at least), but we process them a lot due to other states requirements or just because vets are issuing them. I think it would be important for the user (accredit vet) to be able to clearly identify what is being shipped: animals versus product. Would it be best to keep these separate, or are there situations where someone ships product (e.g. semen) AND animals (e.g. swine)? I haven't seen this, but I don't review all CVIs.

**Comment by mkm1879** [comment]
In Jan 2021 release v2.3
