### ISSUE TITLE
Schema element clarification needed

### ISSUE THREAD

**Issue by BillJacksonTAHC** [AAVLD-USAHA-ITStandards/eCVI#53]
I have a question about the documentation statement in the OtherStateOrZoneStatus element definition in the ecvi2 schema.  It states 'Bovine TB Status', so is the intent to have a secondary Bovine TB Status or is it meant to be used for other diseases?  For instance, I believe Swine has status codes attached pertaining to Brucellosis and Pseudorabies.

**Comment by mkm1879** [comment]
I'm 99.9% certain that is just a copy/paste mistake.  Can anyone on the committee suggest corrected wording for the actual intent?

**Comment by SusanCulp** [comment]
How about:  used to convey any other disease status?

**Comment by StaceySchwabenlander** [comment]
I admit, I'm not certain I fully understand, but if we are looking for alternate wording for miscellaneous disease status, not including TB, it seems @SusanCulp suggestion would make sense. Replace with 'Other Disease Status' seems straight forward. Does that work?

**Comment by dlkdvmphd** [comment]
Agree with "Other Disease Status"

**Comment by mkm1879** [comment]
In Jan 2021 release v2.3
