### ISSUE TITLE
Require at least one Animal, GroupLot, or Product element

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#54]
It strikes me that we could eliminate the strict order and enforce at least one entry by introducing a sequence.
<xs:choice minOccurs="1" maxOccurs="unbounded">

                    <xs:element ref="Animal"/>

                    <xs:element ref="GroupLot"/>

                    <xs:element ref="Product"/>
</xs:choice>

I'll hold off committing this even in draft until I hear pluses and minuses.

**Comment by ryanscholzdvm** [comment]
I would tend to agree that a sequence would be helpful here to allow a bit more flexibility in the XML, as well as making it a bit easier to enforce that you must have at least one child entity to the XML document.

**Comment by dlkdvmphd** [comment]
I think this should be included as we do have submissions that do not have any child entity and result in problems for us.   Some vets do this repeatedly.

**Comment by mkm1879** [comment]
In Jan 2021 release v2.3
