### ISSUE TITLE
Sample CVI Data Question

### ISSUE THREAD

**Issue by BillJacksonTAHC** [AAVLD-USAHA-ITStandards/eCVI#55]
I have a question about the sample CVI data to be processed as part of the vendor approval process.  I am specifically referring to 5 two-month-old Holstein steer.  In the sample data, these steer have no OfficialID connected to any of them, but the ecvi Standard requires that each animal have at least 1 ID.  In this case, is any sample ID left to the discretion of the submitting vendor, or am I overlooking some other detail?

**Comment by StaceySchwabenlander** [comment]
This inquiry was received via email (08/17/2020) and was answered 08/19/2020 via email. 

Response: The eCVI XML schema does not require individual ID for each animal on a CVI. The NASAHO eCVI Standards Subcommittee sample data (given to all eCVI providers as part of the national eCVI approval process) for 5 two-month old Holstein steers is attempting to determine how a provider’s eCVI documents a group of animals on the eCVI.

**Comment by mkm1879** [comment]
Animals without individual IDs are considered--by the schema--to be part of a GroupLot of animals with the same attributes.  Even a single animal, if it lacks ID, would go as a GroupLot element.

**Comment by SusanCulpDVM** [comment]
This issue was discussed at the November 30, 2022 meeting of the eCVI Data Standards Workgroup.  The confusing usage was explained to the original poster on November 12, 2020.   The consensus of the workgroup was to close this issue.
