### ISSUE TITLE
Consider adding an 'Other Description' field for Transportation Mode

### ISSUE THREAD

**Issue by StaceySchwabenlander** [AAVLD-USAHA-ITStandards/eCVI#57]
The Traceability and Technology Committee's eCVI Standards Subcommittee of the National Assembly had a meeting this week. Two points were made that I would like to have documented for this group for consideration. The other issue is #58 

Transportation mode includes the option of 'Other'. Consider adding an 'Other description' field. This will allow users to capture a transportation option of 'Other' AND have that transportation option accurately captured in the 'Other Description' while also transmitting this data in the XML schema so that PDF documents of eCVIs and their accompanying XML data match.

**Comment by SusanCulpDVM** [comment]
@mkm1879 thank you. We can bring this in draft issue up on the call today to see if any other committee members have feedback.
