### ISSUE TITLE
Require transfer to XML of state veterinary license number if it is captured on PDF of eCVI

### ISSUE THREAD

**Issue by StaceySchwabenlander** [AAVLD-USAHA-ITStandards/eCVI#58]
The Traceability and Technology Committee's eCVI Standards Subcommittee of the National Assembly had a meeting this week. Two points were made that I would like to have documented for this group for consideration. Issue #57 is the other issue.

The state license number for a veterinarian is not required to be transmitted within the XML, therefore, if a vendor elects to display this number on the PDF of an eCVI, they are not required to transmit the data in the XML. Consider including a standard to address this so that if the information is presented, it is transferred in the XML.

**Comment by StaceySchwabenlander** [comment]
If a choice had to be made between requiring the state veterinary license number vs the national accreditation number, I would choose to require the national accreditation number first. If both numbers can be required and transmitted via the XML, that would be ideal.

**Comment by mkm1879** [comment]
The technology we are using doesn't allow for the conditionality, "if the number is on the PDF..." so this becomes a policy issue whether or not the NVAP should be required on ALL CVIs.

**Comment by StaceySchwabenlander** [comment]
In case it is helpful to include this in the thread, this is the language I referred to on today's call: 

9 CFR § 161.7   Activities performed by non-accredited veterinarians.
 
(a) Full-time Federal (including military) and State employed veterinarians are authorized to perform functions specified in subchapters B, C, D, and G of this chapter, pursuant to delegation of authority by the Administrator or cooperative agreements, without specific accreditation under the provisions of this subchapter.

I do continue to support requiring an accreditation number on all issued CVIs. I thought it would be important to at least bring up this issue, in case it could prove problematic.

**Comment by SusanCulpDVM** [comment]
This issue was discussed at the November 30, 2022 meeting of the eCVI Data Standards Workgroup.  Since this is outside of the scope of this Workgroup, the consensus was to close this issue and refer it to the NASAHO eCVI Approval Committee.
