### ISSUE TITLE
Need eCVI2 sample XML file

### ISSUE THREAD

**Issue by karthikpdc** [AAVLD-USAHA-ITStandards/eCVI#60]
If there is a sample eCVI2 XML file then it will help developers. Anyone send me a sample?

**Comment by mkm1879** [comment]
The trouble with trying to program from samples is that any sample is ONE sample.  There is, by necessity, a lot of flexibility available by following the schema.  Good XML editors allow you to randomly generate valid examples that span the allowed variation.  Here is one such generated example including optional and repeat elements.  Random choices of types.

[instance1.xml.txt](https://github.com/AAVLD-USAHA-ITStandards/eCVI/files/5802191/instance1.xml.txt)

**Comment by jconlon** [comment]
@karthikpdc you may want to check out this question asked on StackOverflow: [How to generate sample XML documents from their DTD or XSD?](https://stackoverflow.com/questions/17106/how-to-generate-sample-xml-documents-from-their-dtd-or-xsd)

**Comment by SusanCulp** [comment]
@karthikpdc did the feedback provided previously address your request?

**Comment by SusanCulpDVM** [comment]
@mkm1879, a question was asked and feedback provided.  No additional feedback has been requested by the original poster.  Can this issue be closed or is there additional follow up needed here?

**Comment by karthikpdc** [comment]
Yes. This can be closed. No additional follow up needed. Used XMLSpy to validate my XML against schema.
