### ISSUE TITLE
[v2.3] Requirement of non-empty Accession Number

### ISSUE THREAD

**Issue by MichaelJRussell** [AAVLD-USAHA-ITStandards/eCVI#61]
As we test our current XML generation process against the v2.3 schema, we found one issue, and that is that we have some very small number of CVIs which contain tests from "named labs", where accession numbers were not provided. In v2.2, the schema required the `AccessionNumber` attribute on the `Laboratory` element, but there was no verification that it was non-empty. Now, with v2.3, the type has been changed to `nonNullString` in order to enforce the expectation that something be provided in that attribute.

Looking at the data, many of these situations seem to be in-house testing at veterinary clinics/hospitals, as opposed to dedicated diagnostic laboratories, which seem to be better suited to the `Field` element.

In the odd situation where an accession number is not provided, is it acceptable to provide some fallback text for AccessionNumber, such as "Not provided", etc?

**Comment by mkm1879** [comment]
I'd like to hear from others on the committee but I think this might be acceptable other than for equine certificates where the Coggins accession number has long been required.

**Comment by MichaelJRussell** [comment]
I believe this has been answered by #61, unless others from the group have further comments.

**Comment by mkm1879** [comment]
Agree.  Missed that.  It was in the January release.
