### ISSUE TITLE
Should Product elements be allowed together with Animal and Group elements on one CVI?

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#62]
Are there uses cases for both live animals and products on the same eCVI or should this really be a choice between Animal and Group OR Product? 

This never came up during implementation of the Product element in 2.3

**Comment by jconlon** [comment]
Wouldn't this be mixing apples and ~~Orangutans~~ oranges?  And cause more work on the ingestion and backend processing to untangle them?

**Comment by ryanscholzdvm** [comment]
I would venture to suggest that this may be a decision that is beyond the purview of this committee. In terms of data standards, there is nothing wrong with including an animal and product on the same CVI. The issue becomes one of policy as to whether an animal and product SHOULD be included on a CVI. Much the same as whether multiple species of animals can/should be included on a single CVI, I would suggest that this is a decision best left up to the SAHOs in the origin and destination states.

**Comment by SusanCulpDVM** [comment]
> I would venture to suggest that this may be a decision that is beyond the purview of this committee. In terms of data standards, there is nothing wrong with including an animal and product on the same CVI. The issue becomes one of policy as to whether an animal and product SHOULD be included on a CVI. Much the same as whether multiple species of animals can/should be included on a single CVI, I would suggest that this is a decision best left up to the SAHOs in the origin and destination states.

@ryanscholzdvm, I would agree.

**Comment by SusanCulpDVM** [comment]
This issue was discussed at the November 30, 2022 meeting of the eCVI Data Standards Workgroup.  Since this is outside of the scope of this Workgroup, the consensus was to close this issue and refer it to the NASAHO eCVI Approval Committee.
