### ISSUE TITLE
Require Veterinarian to Be Natural Person

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#63]
We have seen the Veterinarian element with only BusinessName.  Should we define a "NaturalPerson" type and require that for Vets?  It would look just like person but not have BusinessName and require FirstName and LastName.

**Comment by BruceLChandler** [comment]
In my opinion it is more important to have the Vet’s first and last name instead of the clinic name as one clinic can potentially have multiple vet’s with no other way to discern which Vet actually issued the CVI without having their specific name on the document.

Bruce L. Chandler    S-129
ADT Tech. Insp. V
5712 Smith Rd.
Bellville, TX, 77418
Cell: 979-203-4329
Bruce.chandler@tahc.texas.gov

**Comment by ryanscholzdvm** [comment]
I would agree that the vet's name is critical. We always tell vets that as far as we are concerned, in the regulatory world, their clinic doesn't exist. The clinic is not accredited to do regulatory work- they are as individuals, regardless of where they happen to be working. I don't mind having the business name included (and for those eCVI platforms that include it on the PDF, we probably need to retain the ability to pass that through the XML), but I do think that it would be helpful to define the vet element somehow to require the first and last name be passed.

**Comment by StaceySchwabenlander** [comment]
I agree we should require FirstName and LastName for the veterinarian issuing the CVI.

**Comment by mkm1879** [comment]
A question came up while editing this.  Should BusinessName continue to be available as an optional element in addition to the first and last name elements?  

Also, I left the single string Name element as an option.  So a provider that really wants to allow the clinic name could cheat and put it there.  But removing that would break other perfectly good implementations.

**Comment by BruceLChandler** [comment]
I also agree that the vet’s name is critical on the eCVI, and the clinic could be optional.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mkm1879** [comment]
As implemented in pendingChanges, I did not include BusinessName at all.  What does the committee think about adding BusinessName back in as optional?

**Comment by SusanCulpDVM** [comment]
@mkm1879 I think that adding BusinessName back in as optional is a good idea.

**Comment by CAllenMN** [comment]
I agree that adding BusinessName back in as an optional field is good.  I assume some vets may want to indicate the clinic they are issuing the document under, especially if they are working at multiple practices.
