### ISSUE TITLE
Sex Other vs. Mixed

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#72]
I've now seen more than one application that sends groups of mixed sex animals (swine and poultry) as GroupLot using the code Other.  That is the best fit.

Should we have Mixed as a choice in SexType?  Should we complicate the schema by only allowing Mixed in GroupLot meaning that SexType would have different definitions the way Name now does.?

**Comment by greenvet2** [comment]
From a pure meaning sense, Mixed ONLY makes sense when applied to GroupLot.  It's very much context dependent.

**Comment by BruceLChandler** [comment]
I agree, it only applies to a group of animals, but it applies not only to sex, but breed and age also.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
