### ISSUE TITLE
MfrRFID type documentation differs from RegEx

### ISSUE THREAD

**Issue by ryanscholzdvm** [AAVLD-USAHA-ITStandards/eCVI#78]
An issue was discovered in the documentation for the Manufacturer RFID identification type where the description references RFID beginning with prefix 901-999, but the actual RegEx (which is correct) requires 900-998. 999 is a reserved prefix that should not be included. This issue was split from #77

**Comment by SusanCulpDVM** [comment]
Included in Release Version 3.0 Update.  Discussed with eCVI Workgroup on January 24, 2024.  All agreed to resolve and close this issue.
