### ISSUE TITLE
Create new International AIN tag type

### ISSUE THREAD

**Issue by ryanscholzdvm** [AAVLD-USAHA-ITStandards/eCVI#79]
The decision was made to create a new official ID type (InternationalAIN) to include all possible international AIN prefixes (except 840) listed in ISO 3166 (https://www.iso.org/iso-3166-country-codes.html). This is split from #77.

**Comment by ryanscholzdvm** [comment]
Special thanks to @mkm1879 for working his magic to pull all of the prefixes from the ISO standard into a pipe-separated list for this new RegEx.

**Comment by SusanCulpDVM** [comment]
Included in Release Version 3.0 Update.  Discussed with eCVI Workgroup on January 24, 2024.  All agreed to resolve and close this issue.
