### ISSUE TITLE
Remove deprecated BOV species code

### ISSUE THREAD

**Issue by ryanscholzdvm** [AAVLD-USAHA-ITStandards/eCVI#80]
The next release is likely to be a major version (3.0) that does not imply any backward compatibility with previous versions. The species code BOV was deprecated previously but left in the standard to allow backward compatibility. Since that will no longer be necessary with the next release, I would propose/recommend that it be removed to prevent inappropriate continued use.

**Comment by ryanscholzdvm** [comment]
There was some discussion today on the call regarding potential issues that this may create with states that still use BOV for digitizing/recording paper CVIs. Justin Smith (KS) mentioned that they do still use BOV, but that they may be able to change that.

**Comment by ryanscholzdvm** [comment]
If BOV is removed as proposed, systems that are still using BOV to record paper CVIs could potentially still accomplish that by using SpeciesOther to record the generic Bovine species. The SpeciesOther type does still allow for a species code to be used.
https://github.com/AAVLD-USAHA-ITStandards/eCVI/blob/bdf1a1dd5b280bef88d5c4011e55bba19dc215ab/ecvi2.xsd#L896-L909

**Comment by SusanCulpDVM** [comment]
Included in Release Version 3.0 Update.  Discussed with eCVI Workgroup on January 24, 2024.  All agreed to resolve and close this issue.
