### ISSUE TITLE
Expand CommodityType list

### ISSUE THREAD

**Issue by ryanscholzdvm** [AAVLD-USAHA-ITStandards/eCVI#81]
The CommodityType enumerated list was added to support products, but only eggs and semen were included. To make the standard more inclusive of other movement types, particularly permitted movements in a disease setting, this list should be expanded to include any products enumerated in Secure Food Supply plans.

**Comment by ryanscholzdvm** [comment]
Here are a few that I found in our SFS plans to get started:
- Embryos
- Milk (Raw)
- Milk (Pasteurized)
- Mohair/Cashmere
- Liquid Egg (Pasteurized)
- Liquid Egg (Non-Pasteurized)
- Shell Eggs (Washed/Sanitized)
- Shell Eggs (Nest Run)
- Shells/Inedible Egg Product
- Hatching Eggs (Layer)
- Hatching Eggs (Broiler)
- Hatching Eggs (Turkey)
- Wool

**Comment by SusanCulpDVM** [comment]
Included in Release Version 3.0 Update.  Discussed with eCVI Workgroup on January 24, 2024.  All agreed to resolve and close this issue.
