### ISSUE TITLE
Make phone type optional

### ISSUE THREAD

**Issue by ryanscholzdvm** [AAVLD-USAHA-ITStandards/eCVI#82]
Currently, a phone type is required to be set from an enumerated list (Unknown, Landline, Cellphone, Fax). In the majority of eCVIs being issued, this seems to be just set as Unknown as the platform often is not requesting that information from the veterinarian. In most cases, even if given the option, most veterinarians are not going to know if a particular phone line is a landline or cellphone anymore, and phone numbers that were once a landline may now have been transferred to cellphones. I would recommend that this attribute be made optional as I’m not sure that it is really adding anything substantive to require an attribute that is just being set to Unknown.

**Comment by SusanCulpDVM** [comment]
Included in Release Version 3.0 Update.  Discussed with eCVI Workgroup on January 24, 2024.  All agreed to resolve and close this issue.
