### ISSUE TITLE
Purpose of Movement

### ISSUE THREAD

**Issue by mkm1879** [AAVLD-USAHA-ITStandards/eCVI#9]
On the 2/8/18 call the Purpose of Movement element came up again.  There is consensus that something is wrong with this element, but not yet a clear suggested improvement.  Some ADT rules are contingent on the purpose of movement so this is an important element, but the current implementation has an inconsistent collection of values with different and ill-defined meanings.

**Comment by KimberlyTsao-USDA** [comment]
The appropriate level of resolution should be driven by how the information will be used. For example, if Purpose of Movement is used to determine whether or not animals should be tested, we then only need to differentiate at a level that can identify those in the context of the record. As a hypothetical example, if all animals going to a rodeo/fair/exhibition need to be tested (and this was the only use for Purpose of Movement), there's no need to provide finer-grained options.

The tradeoff is probably changing categories that users are familiar with - but this is a short-term cost in return for data that are usable for the intended purpose.

I'd suggest further input/information gathering on:
- Why purpose of Movement is important, how the information is used, how it could be more useful
- Categories specific and relevant to those uses

**Comment by mkm1879** [comment]
It sounds from yesterday's call like this actually is correct as a single list and both producers and consumers of CVI data are happy adapting to it.  So just a question of the list completeness.

Asking from ignorance here:  Does the existing list cover things like dairy heifer raising?  Does "feeding" adequately cover things like swine production flows?  Any other specifics we are missing.

**Comment by mkm1879** [comment]
From Justin Smith

All

I have been contemplating the recent group discussion concerning the species/class listing and “imported for the purpose of” choices.  I realize that we need to keep to a proven taxonomy structure as much as possible but I also wonder if we need to keep in mind that the eCVI data exchange standards are intended to exchange the needed information for the lot of animals moving.  I would venture that most state animal health officials would say a description of the animals involved and a concise purpose of movement gives them the needed information to determine if the animals are meeting entry requirements and what risks they might impose.

Although not completely encompassing, below is an example offered by  fellow SAHO’s that I can see meets what I would need to know for an informed decision of what might be required.  This is an example and would welcome your comments and critiques.

Imported for the Purpose of:

Exhibition/Show/Rodeo
Breeding
Competition
Grazing
Feeding to condition
Feeding to slaughter
Direct to slaughter
Laying Hens
Hunting for harvest
Pet
Personal Travel/Transit
Reason for movement:  _________________

**Comment by mkm1879** [comment]
On behalf of Alex Turner

Justin,
I think that is a great list. Thinking through what I see everyday from CVIs I think this would cover most things. The only questions I have would be:
•	Separate out Bison? I think that they come in "Other" currently. Maybe same question for a much smaller number of water buffalo? Both are Bovinae subfamily from a taxonomy standpoint.
•	Add "Recreational" to Purpose?
•	Omit "Direct to Slaughter" as this movement rarely requires a CVI, and as such we don't see a lot of these CVIs. If the movement required a CVI, it would be "Feeding to Slaughter"

**Comment by mkm1879** [comment]
This needs discussion.  Current implementation has just the original values
- show:
- race:
- rodeo:
- sale:
- pet:
- breeding:
- feeding:
- grazing:
- training:
- slaughter:
- medicalTreatment: 

Should we add to are replace with the list Dr. Smith presented?

**Comment by mkm1879** [comment]
From Dee Ellis:
I took the original list of reasons for movement from V1 and combined them with Justin’s and added owner relocating(moving) and evacuation from natural disaster – seen that for hurricanes and fires numerous times. I took out the duplicates. Changed Pet to Companion Animal but could be talked out of that if y’all feel strongly.  So here is a good start for the final draft comprehensive list if y’all want to add on to it or amend it.
•	Racing
•	Sale
•	Grazing
•	Training
•	Slaughter
•	Medical Treatment:
•	Exhibition/Show/Rodeo
•	Breeding
•	Competition
•	Feeding to condition
•	Feeding to slaughter
•	Laying Hens
•	Hunting for harvest
•	Companion Animal
•	Personal Travel/Transit
•	Owner relocating
•	Evacuation from Natural Disaster
•	Reason for movement (Other): _______________


Dee Ellis, DVM MPA
Institute for Infectious Animal Diseases (IIAD)
Texas A&M University System
1500 Research Parkway, Suite B270
College Station, TX 77843-2129
Office 979.862.1380| Cell 512.560.9741
iiad.tamu.edu | @IIADnews

**Comment by mkm1879** [comment]
I have implemented that list in the next iteration to let everyone take a look.  It now consists of a repeatable list of reasons plus a single text element to enter other.  The schema doesn't (can't that I can figure out how) enforce entering a text reason if picking other.

**Comment by mkm1879** [comment]
Leaving these as one "Purpose of Movement" element with the best list we can come up with. Understanding that this is far less than perfect but meets 90% of regulatory needs.
